dojo.require("dijit.form.Slider");dojo.require("dijit.form.Button");dojo.require("dijit.Menu");var context,canvas,colorScheme="green",picRadius=null,starRadius=null,starTemp=null,winWidth,winHeight,equationContainer,metricLine,buttonContainer,radiusContainer,tempContainer,radiusSlider,tempSlider,radText,radBase,radExp,tempText,lumBase,lumExp,radiusSolar,tempSolar,lumSolarBase,lumSolarExp,closeLayerContainer,openLayer,oldX=[],oldY=[],newX=[],newY=[],oldTotalSeparation,startTotalSeparation;
function getTouchX(a){var c=[],b;if(!a)a=window.event;if(a.touches[0].pageX)for(b=0;b<a.touches.length;b++)c[b]=a.touches[b].pageX;return c}function getTouchY(a){var c=[],b;if(!a)a=window.event;if(a.touches[0].pageY)for(b=0;b<a.touches.length;b++)c[b]=a.touches[b].pageY;return c}
function getColorFromTemp(a){var c,b,d,e;a<1E3?a=1E3:a>4E4&&(a=4E4);b=Math.log(a)/Math.LN10;d=b*b;e=b*d;c=22686.34111-b*15082.52755+d*3375.333832-e*252.4073853;c<0?c=0:c>255&&(c=255);a=a<=6500?-811.6499145+b*36.97365953+d*160.7861677-e*25.57573664:13836.23586-b*9069.078214+d*2015.254756-e*149.7766966;b=-11545.34298+b*8529.658165-d*2150.198586+e*190.0306573;b<0?b=0:b>255&&(b=255);return"rgb("+String(Math.round(c))+", "+String(Math.round(a))+", "+String(Math.round(b))+")"}
function presetMenuItem(a,c,b){return new dijit.MenuItem({label:b,onClick:function(){radiusSlider.set("value",Math.LOG10E*Math.log(a));tempSlider.set("value",Math.LOG10E*Math.log(c));tempText.style.color=colorScheme;tempSolar.style.color=colorScheme;radText.style.color=colorScheme;radiusSolar.style.color=colorScheme}})}
function layerButton(a,c){return new dijit.MenuItem({label:a,onClick:function(){closeLayerContainer.style.display="block";openLayer.style.display="none";c.style.display="block";openLayer=c;buttonContainer.style.marginTop="10px";buttonContainer.style.marginRight="10px"}})}
function adjustButton(a,c,b,d){return new dijit.form.Button({label:d,onClick:function(){c.set("value",Math.LOG10E*Math.log((1+0.01*b)*Math.pow(10,c.value)));c.value>c.maximum?c.set("value",c.maximum):c.value<c.minimum&&c.set("value",c.minimum)}},a)}function snapButton(a,c,b,d){d=new dijit.form.Button({label:d,style:"padding:0px;margin:0px;",onClick:function(){c.set("value",Math.LOG10E*Math.log(b))}},a);dojo.byId(a+"_label").style.padding="0px";return d}
function updateEquation(){var a=String((starRadius*696E6).toExponential(2)),c=a.slice(0,4),a=a.slice(6),b=Math.pow(starRadius*696E6,2)*Math.pow(starTemp,4)*4*Math.PI*5.6704E-8,d=String(b.toExponential(1)),e=d.slice(0,3),d=d.slice(5),h=String(starRadius),i=String((starTemp/5780).toFixed(2)),f=b/3.8526E26,g;f<999.95&&f>=0.01?(b=f>=10?f.toFixed(1):f>=0.1?f.toFixed(2):f.toFixed(3),g=""):(g=String((b/3.9876E26).toExponential(2)),b=g.slice(0,4)+"x10",g=g.slice(6),f<1&&(g="-"+g));radBase.innerHTML=c;radExp.innerHTML=
a;tempText.innerHTML=starTemp;lumBase.innerHTML=e;lumExp.innerHTML=d;radiusSolar.innerHTML=h;tempSolar.innerHTML=i;lumSolarBase.innerHTML=b;lumSolarExp.innerHTML=g}function drawStar(){context.clearRect(0,0,canvas.width,canvas.height);context.moveTo(canvas.width/2,canvas.height/2);context.beginPath();context.arc(canvas.width/2,canvas.height/2,picRadius/200*(canvas.width-20),0,Math.PI*2);context.fillStyle=getColorFromTemp(starTemp);context.fill();context.closePath()}
function layout(){metricLine.style.display="inline";winWidth>winHeight?(canvas.height=winHeight-3,canvas.width=canvas.height,canvas.style.left="50%",canvas.style.top="0px",canvas.style.marginLeft="-"+String(winHeight/2)+"px",canvas.style.marginTop="0px"):(canvas.width=winWidth-3,canvas.height=canvas.width,canvas.style.left="0px",canvas.style.top="50%",canvas.style.marginTop="-"+String(winWidth/2)+"px",canvas.style.marginLeft="0px");if(equationContainer.offsetHeight>winHeight-140)metricLine.style.display=
"none";drawStar()}
dojo.addOnLoad(function(){canvas=document.getElementById("myCanvas");context=canvas.getContext("2d");dojo.byId("body").style.color=colorScheme;dojo.byId("body").style.borderColor=colorScheme;starTemp=5780;starRadius=1;picRadius=(Math.LOG10E*Math.log(starRadius)+1)*25+1;equationContainer=document.getElementById("equationContainer");metricLine=document.getElementById("metricLine");buttonContainer=document.getElementById("buttonContainer");radiusContainer=document.getElementById("radiusContainer");tempContainer=
document.getElementById("tempContainer");radText=dojo.byId("radText");radBase=dojo.byId("radBase");radExp=dojo.byId("radExp");tempText=dojo.byId("tempText");lumBase=dojo.byId("lumBase");lumExp=dojo.byId("lumExp");radiusSolar=dojo.byId("radiusSolar");tempSolar=dojo.byId("tempSolar");lumSolarBase=dojo.byId("lumSolarBase");lumSolarExp=dojo.byId("lumSolarExp");radiusSlider=new dijit.form.HorizontalSlider({name:"radiusSlider",value:(picRadius-1)/25-1,minimum:-1.0001,maximum:3,intermediateChanges:!0,showButtons:!1,
onChange:function(a){picRadius=(a+1)*25+1;starRadius=Math.pow(10,a).toFixed(2);updateEquation();drawStar();radText.style.color="rgb(137, 207, 240)";radiusSolar.style.color="rgb(137, 207, 240)";tempText.style.color=colorScheme;tempSolar.style.color=colorScheme}},"radiusSlider");tempSlider=new dijit.form.HorizontalSlider({name:"tempSlider",value:Math.LOG10E*Math.log(starTemp),minimum:3.39791,maximum:4.60206,intermediateChanges:!0,showButtons:!1,onChange:function(a){starTemp=Math.round(Math.pow(10,a));
updateEquation();drawStar();radText.style.color=colorScheme;radiusSolar.style.color=colorScheme;tempText.style.color="rgb(137, 207, 240)";tempSolar.style.color="rgb(137, 207, 240)"}},"tempSlider");var a=new dijit.Menu({style:"display: none;"});a.addChild(presetMenuItem(1,5780,"The Sun"));a.addChild(presetMenuItem(800,3500,"Antares"));a.addChild(presetMenuItem(200,8525,"Deneb"));a.addChild(presetMenuItem(50,5600,"Beta Aquarii"));a.addChild(presetMenuItem(30,7200,"Polaris"));a.addChild(presetMenuItem(7.4,
22400,"Spica"));a.addChild(presetMenuItem(1.8,22E3,"Alkaid"));a.addChild(presetMenuItem(0.15,3134,"Barnard's Star"));a=new dijit.form.DropDownButton({label:"Presets",name:"presetButtonDojo",dropDown:a,id:"presetButtonDojo"});dojo.byId("presetButton").appendChild(a.domNode);closeLayerContainer=document.getElementById("closeLayerContainer");var a=document.getElementById("objectives"),c=document.getElementById("background"),b=document.getElementById("exercises"),d=document.getElementById("about");new dijit.form.Button({label:"Close",
name:"closeLayerButton",onClick:function(){openLayer.style.display="none";closeLayerContainer.style.display="none";buttonContainer.style.marginTop="0px";buttonContainer.style.marginRight="0px"}},"closeLayer");openLayer=d;var e=new dijit.Menu({style:"display: none;"});e.addChild(layerButton("Objectives",a));e.addChild(layerButton("Background",c));e.addChild(layerButton("Exercises",b));e.addChild(layerButton("About",d));a=new dijit.form.DropDownButton({label:"Info",name:"infoButtonDojo",dropDown:e,
id:"infoButtonDojo"});dojo.byId("infoButton").appendChild(a.domNode);adjustButton("radiusDecButton",radiusSlider,-1,"<");adjustButton("radiusIncButton",radiusSlider,1,">");adjustButton("tempDecButton",tempSlider,-1,"<");adjustButton("tempIncButton",tempSlider,1,">");snapButton("radSnap1",radiusSlider,0.1,".1");snapButton("radSnap2",radiusSlider,1,"1");snapButton("radSnap3",radiusSlider,10,"10");snapButton("radSnap4",radiusSlider,100,"100");snapButton("radSnap5",radiusSlider,1E3,"1k");snapButton("tempSnap1",
tempSlider,2500,"2.5k");snapButton("tempSnap2",tempSlider,5E3,"5k");snapButton("tempSnap3",tempSlider,1E4,"10k");snapButton("tempSnap4",tempSlider,2E4,"20k");snapButton("tempSnap5",tempSlider,4E4,"40k");updateEquation();drawStar();winWidth=window.innerWidth;winHeight=window.innerHeight;layout();dojo.connect(window,"onresize",function(){winWidth=window.innerWidth;winHeight=window.innerHeight;layout()});dojo.connect(window,"onmouseup",function(){tempText.style.color=colorScheme;tempSolar.style.color=
colorScheme;radText.style.color=colorScheme;radiusSolar.style.color=colorScheme});dojo.connect(window,"ontouchend",function(){tempText.style.color=colorScheme;tempSolar.style.color=colorScheme;radText.style.color=colorScheme;radiusSolar.style.color=colorScheme});dojo.connect(radiusContainer,"ontouchmove",function(a){var b;if(!a)a=window.event;if(a.touches[0].pageX)b=a.touches[0].pageX;radiusSlider.set("value",(b-17)/(radiusContainer.offsetWidth-34)*(radiusSlider.maximum-radiusSlider.minimum)+radiusSlider.minimum);
radiusSlider.value>radiusSlider.maximum?radiusSlider.set("value",radiusSlider.maximum):radiusSlider.value<radiusSlider.minimum&&radiusSlider.set("value",radiusSlider.minimum)});dojo.connect(tempContainer,"ontouchmove",function(a){var b;if(!a)a=window.event;if(a.touches[0].pageX)b=a.touches[0].pageX;tempSlider.set("value",(b-17)/(tempContainer.offsetWidth-34)*(tempSlider.maximum-tempSlider.minimum)+tempSlider.minimum);tempSlider.value>tempSlider.maximum?tempSlider.set("value",tempSlider.maximum):tempSlider.value<
tempSlider.minimum&&tempSlider.set("value",tempSlider.minimum)});dojo.connect(dojo.byId("unscrollable"),"ontouchstart",function(a){oldX=getTouchX(a);oldY=getTouchY(a);if(oldX.length>1){var b=0,a=0,c;for(c in oldX)b+=oldX[c],a+=oldY[c];b/=oldX.length;a/=oldY.length;oldTotalSeparation=0;for(c in oldX)oldTotalSeparation+=Math.sqrt(Math.pow(oldX[c]-b,2)+Math.pow(oldY[c]-a,2));startTotalSeparation=oldTotalSeparation}});dojo.connect(dojo.byId("unscrollable"),"ontouchmove",function(a){a.preventDefault();
newX=getTouchX(a);if(newX.length>1){newY=getTouchY(a);var b=a=0,c;for(c in newX)a+=newX[c],b+=newY[c];a/=newX.length;b/=newY.length;var d=0;for(c in newX)d+=Math.sqrt(Math.pow(newX[c]-a,2)+Math.pow(newY[c]-b,2));oldTotalSeparation>0&&newX.length==oldX.length&&(picRadius*=d/oldTotalSeparation,picRadius<1?picRadius=1:picRadius>101&&(picRadius=101),radiusSlider.set("value",(picRadius-1)/25-1));oldTotalSeparation=d}})});