dojo.require("dijit.form.Button");dojo.require("dijit.Menu");var canvas,context,colorScheme="rgb(137, 207, 240)",buttonContainer,closeLayerContainer,centerButtonContainer,openLayer,infoMenuItems=[],galaxies=[],selected,scrollHandled=!1,width,height,offsetX=0,offsetY=0,picSize=100,defaultBuffer,buffer,scaleFactor=1,oldX=[],oldY=[],newX=[],newY=[],oldTotalSeparation,startTotalSeparation,oldScaleFactor=1,dragging=!1,selecting=!1;
function infoMenuItem(b,e){return new dijit.MenuItem({label:b,onClick:function(){closeLayerContainer.style.display="block";openLayer.style.display="none";e.style.display="block";openLayer=e;buttonContainer.style.marginTop="10px";buttonContainer.style.marginRight="10px"}})}
function drawArrows(){context.clearRect(0,0,width,height);var b,e,c,f,d,g,a;for(a in galaxies)if(-picSize<galaxies[a].xPos&&galaxies[a].xPos<width&&-picSize<galaxies[a].yPos&&galaxies[a].yPos<height)b=(galaxies[a].xPos-selected.xPos)/scaleFactor,e=(galaxies[a].yPos-selected.yPos)/scaleFactor,c=galaxies[a].xPos+50*scaleFactor,f=galaxies[a].yPos+50*scaleFactor,d=c+0.1*b,g=f+0.1*e,context.beginPath(),context.moveTo(c,f),context.lineTo(d,g),f=Math.sqrt(b*b+e*e),c=Math.sqrt(f/50),context.lineWidth=c,context.strokeStyle=
"red",context.stroke(),context.closePath(),b=c*b*2/f,e=c*e*2/f,context.beginPath(),context.moveTo(d+b,g+e),context.lineTo(d+e,g-b),context.lineTo(d-e,g+b),context.lineTo(d+b,g+e),context.closePath(),context.fillStyle="red",context.fill()}function getMouseX(b){if(!b)b=window.event;if(b.pageX)return[b.pageX];else if(b.clientX)return[b.clientX+document.body.scrollLeft+document.documentElement.scrollLeft];return oldX}
function getMouseY(b){if(!b)b=window.event;if(b.pageY)return[b.pageY];else if(b.clientY)return[b.clientY+document.body.scrollTop+document.documentElement.scrollTop];return oldY}function getTouchX(b){var e=[],c;if(!b)b=window.event;if(b.touches[0].pageX)for(c=0;c<b.touches.length;c++)e[c]=b.touches[c].pageX;return e}function getTouchY(b){var e=[],c;if(!b)b=window.event;if(b.touches[0].pageY)for(c=0;c<b.touches.length;c++)e[c]=b.touches[c].pageY;return e}
function layout(){canvas.width=window.innerWidth;canvas.height=window.innerHeight;width=canvas.width;height=canvas.height;drawArrows()}
function selectGalaxy(b,e){for(var c in galaxies)if(galaxies[c].xPos<b&&b<galaxies[c].xPos+picSize&&galaxies[c].yPos<e&&e<galaxies[c].yPos+picSize){var f=selected.style.left,d=selected.style.top,g=selected.xPos,a=selected.yPos,h=selected.src;selected.style.left=galaxies[c].style.left;selected.style.top=galaxies[c].style.top;selected.xPos=galaxies[c].xPos;selected.yPos=galaxies[c].yPos;selected.src=galaxies[c].src;galaxies[c].style.left=f;galaxies[c].style.top=d;galaxies[c].xPos=g;galaxies[c].yPos=
a;galaxies[c].src=h;drawArrows();break}}
function stretchSpace(){var b=0,e=0,c;for(c in newX)b+=newX[c],e+=newY[c];b/=newX.length;e/=newY.length;var f=0;for(c in newX)f+=Math.sqrt(Math.pow(newX[c]-b,2)+Math.pow(newY[c]-e,2));if(oldTotalSeparation>0&&newX.length==oldX.length){scaleFactor*=f/oldTotalSeparation;scaleFactor<0.2?scaleFactor=0.2:scaleFactor>5&&(scaleFactor=5);picSize=100*scaleFactor;buffer=defaultBuffer*scaleFactor;c=scaleFactor/oldScaleFactor;for(var d in galaxies)galaxies[d].style.width=String(picSize)+"px",galaxies[d].style.height=
String(picSize)+"px",galaxies[d].xPos=b-c*(b-galaxies[d].xPos),galaxies[d].yPos=e-c*(e-galaxies[d].yPos),galaxies[d].style.left=String(galaxies[d].xPos)+"px",galaxies[d].style.top=String(galaxies[d].yPos)+"px";selected.style.width=String(picSize)+"px";selected.style.height=String(picSize)+"px";selected.xPos=b-c*(b-selected.xPos);selected.yPos=e-c*(e-selected.yPos);selected.style.left=String(selected.xPos)+"px";selected.style.top=String(selected.yPos)+"px";selected.style.borderRadius=String(picSize/
2)+"px";oldScaleFactor=scaleFactor}oldTotalSeparation=f}
function moveSpace(b,e){selecting&&(selecting=!1);newX=b;newY=e;newX.length>1&&stretchSpace();var c=0,f=0,d;for(d in newX)c+=newX[d]-oldX[d],f+=newY[d]-oldY[d];selected.xPos+=c;selected.yPos+=f;selected.style.left=String(selected.xPos)+"px";selected.style.top=String(selected.yPos)+"px";Math.abs(c)>buffer*2&&(c=buffer*2);Math.abs(f)>buffer*2&&(f=buffer*2);for(d in galaxies){galaxies[d].xPos+=c;galaxies[d].yPos+=f;if(galaxies[d].xPos<width/2-buffer)galaxies[d].xPos=Math.round(Math.random()*c)+width/
2+buffer-c,galaxies[d].yPos=Math.round(Math.random()*2*buffer)-buffer+height/2,galaxies[d].src="Galaxy"+String(Math.ceil(Math.random()*4))+".gif";else if(galaxies[d].xPos>width/2+buffer)galaxies[d].xPos=Math.round(Math.random()*c)+width/2-buffer,galaxies[d].yPos=Math.round(Math.random()*2*buffer)-buffer+height/2,galaxies[d].src="Galaxy"+String(Math.ceil(Math.random()*4))+".gif";else if(galaxies[d].yPos<height/2-buffer)galaxies[d].yPos=Math.round(Math.random()*f)+height/2+buffer-f,galaxies[d].xPos=
Math.round(Math.random()*2*buffer)-buffer+width/2,galaxies[d].src="Galaxy"+String(Math.ceil(Math.random()*4))+".gif";else if(galaxies[d].yPos>height/2+buffer)galaxies[d].yPos=Math.round(Math.random()*f)+height/2-buffer,galaxies[d].xPos=Math.round(Math.random()*2*buffer)-buffer+width/2,galaxies[d].src="Galaxy"+String(Math.ceil(Math.random()*4))+".gif";galaxies[d].style.left=String(galaxies[d].xPos)+"px";galaxies[d].style.top=String(galaxies[d].yPos)+"px"}drawArrows();oldX=newX;oldY=newY}
dojo.addOnLoad(function(){canvas=document.getElementById("myCanvas");context=canvas.getContext("2d");canvas.width=window.innerWidth;canvas.height=window.innerHeight;width=canvas.width;height=canvas.height;dojo.byId("body").style.color=colorScheme;dojo.byId("body").style.borderColor=colorScheme;defaultBuffer=width>height?canvas.width*2.5+150:canvas.height*2.5+150;buffer=defaultBuffer*scaleFactor;var b;for(b=0;b<50;b++)galaxies[b]=document.getElementById("g"+String(b)),galaxies[b].xPos=Math.round(Math.random()*
2*buffer)-buffer+width/2,galaxies[b].yPos=Math.round(Math.random()*2*buffer)-buffer+height/2,galaxies[b].style.left=String(galaxies[b].xPos)+"px",galaxies[b].style.top=String(galaxies[b].yPos)+"px",galaxies[b].src="Galaxy"+String(Math.ceil(Math.random()*4))+".gif";selected=document.getElementById("selected");selected.xPos=width/2-50;selected.yPos=height/2-50;selected.style.left=String(selected.xPos)+"px";selected.style.top=String(selected.yPos)+"px";selected.src="Galaxy"+String(Math.ceil(Math.random()*
4))+".gif";buttonContainer=document.getElementById("buttonContainer");closeLayerContainer=document.getElementById("closeLayerContainer");centerButtonContainer=document.getElementById("centerButtonContainer");b=document.getElementById("objectives");var e=document.getElementById("background"),c=document.getElementById("exercises"),f=document.getElementById("about");new dijit.form.Button({label:"Close",name:"closeLayerButton",onClick:function(){openLayer.style.display="none";closeLayerContainer.style.display=
"none";buttonContainer.style.marginTop="0px";buttonContainer.style.marginRight="0px"}},"closeLayer");dojo.connect(closeLayerContainer,"ontouchmove",function(a){a.preventDefault()});dojo.connect(closeLayerContainer,"onmousemove",function(a){a.preventDefault()});new dijit.form.Button({label:"Center",name:"centerButton",onClick:function(){oldX=[selected.xPos];oldY=[selected.yPos];moveSpace([(width-picSize)/2],[(height-picSize)/2])}},"centerButton");dojo.connect(centerButtonContainer,"ontouchmove",function(a){a.preventDefault()});
dojo.connect(centerButtonContainer,"onmousemove",function(a){a.preventDefault()});openLayer=f;var d=new dijit.Menu({style:"display: none;"});infoMenuItems[0]=infoMenuItem("Objectives",b);infoMenuItems[1]=infoMenuItem("Background",e);infoMenuItems[2]=infoMenuItem("Exercises",c);infoMenuItems[3]=infoMenuItem("About",f);for(var g in infoMenuItems)d.addChild(infoMenuItems[g]);g=new dijit.form.DropDownButton({label:"Info",name:"infoButtonDojo",dropDown:d,id:"infoButtonDojo"});d=dojo.byId("infoButton");
d.appendChild(g.domNode);dojo.connect(d,"ontouchmove",function(a){a.preventDefault()});dojo.connect(d,"onmousemove",function(a){a.preventDefault()});g=dojo.byId("unscrollable");dojo.connect(g,"onmousedown",function(a){dragging=selecting=!0;oldX=getMouseX(a);oldY=getMouseY(a)});dojo.connect(g,"ontouchstart",function(a){selecting=!0;oldX=getTouchX(a);oldY=getTouchY(a);if(oldX.length>1){var b=0,a=0,c;for(c in oldX)b+=oldX[c],a+=oldY[c];b/=oldX.length;a/=oldY.length;oldTotalSeparation=0;for(c in oldX)oldTotalSeparation+=
Math.sqrt(Math.pow(oldX[c]-b,2)+Math.pow(oldY[c]-a,2));startTotalSeparation=oldTotalSeparation}});dojo.connect(g,"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(g,"ontouchmove",function(a){a.preventDefault();moveSpace(getTouchX(a),getTouchY(a))});dojo.connect(g,"ondragstart",function(){return!1});dojo.connect(g,"mousewheel",function(a){a.wheelDelta>0?(oldX=[a.clientX+27,a.clientX-27],oldY=[a.clientY+36,a.clientY-36],oldTotalSeparation=90,
moveSpace([a.clientX+30,a.clientX-30],[a.clientY+40,a.clientY-40])):(oldX=[a.clientX+30,a.clientX-30],oldY=[a.clientY+40,a.clientY-40],oldTotalSeparation=100,moveSpace([a.clientX+27,a.clientX-27],[a.clientY+36,a.clientY-36]));scrollHandled||(scrollHandled=!0)});dojo.connect(g,"DOMMouseScroll",function(a){scrollHandled||(a.detail<0?(oldX=[a.clientX+27,a.clientX-27],oldY=[a.clientY+36,a.clientY-36],oldTotalSeparation=90,moveSpace([a.clientX+30,a.clientX-30],[a.clientY+40,a.clientY-40])):(oldX=[a.clientX+
30,a.clientX-30],oldY=[a.clientY+40,a.clientY-40],oldTotalSeparation=100,moveSpace([a.clientX+27,a.clientX-27],[a.clientY+36,a.clientY-36])))});dojo.connect(g,"onmouseup",function(){dragging=!1;selecting&&oldX.length==1&&selectGalaxy(oldX[0],oldY[0])});dojo.connect(g,"ontouchend",function(){selecting&&oldX.length==1&&selectGalaxy(oldX[0],oldY[0])});dojo.connect(dojo.byId("buttonContainer"),"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(b,
"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(e,"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(c,"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(f,"onmousemove",function(a){dragging&&(a.preventDefault(),moveSpace(getMouseX(a),getMouseY(a)))});dojo.connect(dojo.byId("buttonContainer"),"onmouseup",function(){dragging=
!1});dojo.connect(b,"onmouseup",function(){dragging=!1});dojo.connect(e,"onmouseup",function(){dragging=!1});dojo.connect(c,"onmouseup",function(){dragging=!1});dojo.connect(f,"onmouseup",function(){dragging=!1});layout();window.onresize=function(){layout()}});